# Generated by Django 4.2.17 on 2025-01-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagealt',
            name='dt_date_debut_stg_alt',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stagealt',
            name='dt_date_fin_stg_alt',
            field=models.DateField(null=True),
        ),
    ]
