# Generated by Django 4.2.17 on 2025-01-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_stagealt_dt_date_debut_stg_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagealt',
            name='duree_stg_alt',
            field=models.IntegerField(null=True),
        ),
    ]
