# Generated by Django 4.2.17 on 2025-01-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_stagealt_duree_stg_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='id_connection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='id_connection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='secretaire',
            name='id_connection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tuteurpro',
            name='id_connection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
