# Generated by Django 4.2.17 on 2025-01-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_etudiant_id_connection_professeur_id_connection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='id_salle',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
