# Generated by Django 4.2.17 on 2025-01-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_salle_id_salle'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='nb_alternant_but2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='nb_alternant_but3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='nb_stagaire_but2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='nb_stagaire_but3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
