# Generated by Django 4.2.17 on 2025-01-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_professeur_nb_alternant_but2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='nb_alternant_but2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='nb_alternant_but3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='nb_stagaire_but2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='nb_stagaire_but3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
