-- Generated by Mocodo 4.2.11

CREATE TABLE ACCUEIL (
  PRIMARY KEY (id_stg_alt, id_entp),
  id_stg_alt VARCHAR(42) NOT NULL,
  id_entp    VARCHAR(42) NOT NULL
);

CREATE TABLE ANNEE (
  PRIMARY KEY (id_annee),
  id_annee VARCHAR(42) NOT NULL,
  annee    VARCHAR(42)
);

CREATE TABLE DATE_HORAIRE (
  PRIMARY KEY (id_dt_hr),
  id_dt_hr VARCHAR(42) NOT NULL,
  date     VARCHAR(42),
  heure    VARCHAR(42)
);

CREATE TABLE ELEVE (
  PRIMARY KEY (id_eleve),
  id_eleve       VARCHAR(42) NOT NULL,
  num_etu        VARCHAR(42),
  mail_univ      VARCHAR(42),
  civilite_eleve VARCHAR(42),
  nom_eleve      VARCHAR(42),
  prenom_eleve   VARCHAR(42),
  ine            VARCHAR(42)
);

CREATE TABLE ENTREPRISE (
  PRIMARY KEY (id_entp),
  id_entp    VARCHAR(42) NOT NULL,
  nom_entp   VARCHAR(42),
  cp_entp    VARCHAR(42),
  ville_entp VARCHAR(42)
);

CREATE TABLE EST_DANS_PROMO (
  PRIMARY KEY (id_eleve, id_promo, id_annee),
  id_eleve VARCHAR(42) NOT NULL,
  id_promo VARCHAR(42) NOT NULL,
  id_annee VARCHAR(42) NOT NULL
);

CREATE TABLE FAIT (
  PRIMARY KEY (id_stg_alt, id_eleve),
  id_stg_alt VARCHAR(42) NOT NULL,
  id_eleve   VARCHAR(42) NOT NULL
);

CREATE TABLE PROFESSEUR (
  PRIMARY KEY (id_tut_univ),
  id_tut_univ       VARCHAR(42) NOT NULL,
  civilite_tut_univ VARCHAR(42),
  nom_tut_univ      VARCHAR(42),
  prenom_tut_univ   VARCHAR(42),
  mail_tut_univ     VARCHAR(42)
);

CREATE TABLE PROMOTION (
  PRIMARY KEY (id_promo),
  id_promo    VARCHAR(42) NOT NULL,
  nom_promo   VARCHAR(42),
  id_tut_univ VARCHAR(42) NOT NULL
);

CREATE TABLE SALLE (
  PRIMARY KEY (id_salle),
  id_salle  VARCHAR(42) NOT NULL,
  nom_salle VARCHAR(42)
);

CREATE TABLE SECRETAIRE (
  PRIMARY KEY (id_sec),
  id_sec VARCHAR(42) NOT NULL,
  nom    VARCHAR(42),
  prenom VARCHAR(42),
  mail   VARCHAR(42)
);

CREATE TABLE SOUTENANCE (
  PRIMARY KEY (id_sout),
  id_sout     VARCHAR(42) NOT NULL,
  id_stg_alt  VARCHAR(42) NOT NULL,
  id_dt_hr    VARCHAR(42) NOT NULL,
  id_salle    VARCHAR(42) NOT NULL,
  id_tut_univ VARCHAR(42) NOT NULL
);

CREATE TABLE STAGE_ALTERNANCE (
  PRIMARY KEY (id_stg_alt),
  id_stg_alt           VARCHAR(42) NOT NULL,
  titre_stg_alt        VARCHAR(42),
  theme_stg_alt        VARCHAR(42),
  intitule_env_stg_alt VARCHAR(42),
  dtdeb_stg_alt        VARCHAR(42),
  dtfin_stg_alt        VARCHAR(42),
  duree                VARCHAR(42),
  id_tut_pro           VARCHAR(42) NOT NULL,
  id_tut_univ          VARCHAR(42) NOT NULL
);

CREATE TABLE TUTEUR_PRO (
  PRIMARY KEY (id_tut_pro),
  id_tut_pro       VARCHAR(42) NOT NULL,
  civilite_tut_pro VARCHAR(42),
  nom_tut_pro      VARCHAR(42),
  prenom_tut_pro   VARCHAR(42),
  tel_tut_pro      VARCHAR(42),
  gsm_tut_pro      VARCHAR(42),
  mail_tut_pro     VARCHAR(42),
  id_entp          VARCHAR(42) NOT NULL
);

ALTER TABLE ACCUEIL ADD FOREIGN KEY (id_entp) REFERENCES ENTREPRISE (id_entp);
ALTER TABLE ACCUEIL ADD FOREIGN KEY (id_stg_alt) REFERENCES STAGE_ALTERNANCE (id_stg_alt);

ALTER TABLE EST_DANS_PROMO ADD FOREIGN KEY (id_annee) REFERENCES ANNEE (id_annee);
ALTER TABLE EST_DANS_PROMO ADD FOREIGN KEY (id_promo) REFERENCES PROMOTION (id_promo);
ALTER TABLE EST_DANS_PROMO ADD FOREIGN KEY (id_eleve) REFERENCES ELEVE (id_eleve);

ALTER TABLE FAIT ADD FOREIGN KEY (id_eleve) REFERENCES ELEVE (id_eleve);
ALTER TABLE FAIT ADD FOREIGN KEY (id_stg_alt) REFERENCES STAGE_ALTERNANCE (id_stg_alt);

ALTER TABLE PROMOTION ADD FOREIGN KEY (id_tut_univ) REFERENCES PROFESSEUR (id_tut_univ);

ALTER TABLE SOUTENANCE ADD FOREIGN KEY (id_tut_univ) REFERENCES PROFESSEUR (id_tut_univ);
ALTER TABLE SOUTENANCE ADD FOREIGN KEY (id_salle) REFERENCES SALLE (id_salle);
ALTER TABLE SOUTENANCE ADD FOREIGN KEY (id_dt_hr) REFERENCES DATE_HORAIRE (id_dt_hr);
ALTER TABLE SOUTENANCE ADD FOREIGN KEY (id_stg_alt) REFERENCES STAGE_ALTERNANCE (id_stg_alt);

ALTER TABLE STAGE_ALTERNANCE ADD FOREIGN KEY (id_tut_univ) REFERENCES PROFESSEUR (id_tut_univ);
ALTER TABLE STAGE_ALTERNANCE ADD FOREIGN KEY (id_tut_pro) REFERENCES TUTEUR_PRO (id_tut_pro);

ALTER TABLE TUTEUR_PRO ADD FOREIGN KEY (id_entp) REFERENCES ENTREPRISE (id_entp);
