-- Generated by Mocodo 4.2.10

CREATE TABLE App_Stagiaire (
  PRIMARY KEY (id_app_stag),
  id_app_stag     VARCHAR(42) NOT NULL,
  nom_app_stag    VARCHAR(42),
  prenom_app_stag VARCHAR(42),
  id_tpro         VARCHAR(42) NOT NULL,
  id_entp         VARCHAR(42) NOT NULL,
  id_prof         VARCHAR(42) NOT NULL,
  id_promo        VARCHAR(42) NOT NULL
);

CREATE TABLE Entreprise (
  PRIMARY KEY (id_entp),
  id_entp  VARCHAR(42) NOT NULL,
  nom_entp VARCHAR(42)
);

CREATE TABLE Professeur (
  PRIMARY KEY (id_prof),
  id_prof  VARCHAR(42) NOT NULL,
  nom_prof VARCHAR(42)
);

CREATE TABLE Promotion (
  PRIMARY KEY (id_promo),
  id_promo  VARCHAR(42) NOT NULL,
  nom_promo VARCHAR(42)
);

CREATE TABLE Salle (
  PRIMARY KEY (id_salle),
  id_salle  VARCHAR(42) NOT NULL,
  nom_salle VARCHAR(42)
);

CREATE TABLE Soutenance (
  PRIMARY KEY (id_sout),
  id_sout      VARCHAR(42) NOT NULL,
  date_sout    VARCHAR(42),
  horaire_sout VARCHAR(42),
  id_tpro      VARCHAR(42) NOT NULL,
  id_salle     VARCHAR(42) NOT NULL,
  id_prof_1    VARCHAR(42) NOT NULL,
  id_prof_2    VARCHAR(42) NOT NULL,
  id_app_stag  VARCHAR(42) NOT NULL
);

CREATE TABLE Tuteur_Pro (
  PRIMARY KEY (id_tpro),
  id_tpro  VARCHAR(42) NOT NULL,
  nom_tpro VARCHAR(42),
  id_entp  VARCHAR(42) NOT NULL
);

ALTER TABLE App_Stagiaire ADD FOREIGN KEY (id_promo) REFERENCES Promotion (id_promo);
ALTER TABLE App_Stagiaire ADD FOREIGN KEY (id_prof) REFERENCES Professeur (id_prof);
ALTER TABLE App_Stagiaire ADD FOREIGN KEY (id_entp) REFERENCES Entreprise (id_entp);
ALTER TABLE App_Stagiaire ADD FOREIGN KEY (id_tpro) REFERENCES Tuteur_Pro (id_tpro);

ALTER TABLE Soutenance ADD FOREIGN KEY (id_app_stag) REFERENCES App_Stagiaire (id_app_stag);
ALTER TABLE Soutenance ADD FOREIGN KEY (id_prof_2) REFERENCES Professeur (id_prof);
ALTER TABLE Soutenance ADD FOREIGN KEY (id_prof_1) REFERENCES Professeur (id_prof);
ALTER TABLE Soutenance ADD FOREIGN KEY (id_salle) REFERENCES Salle (id_salle);
ALTER TABLE Soutenance ADD FOREIGN KEY (id_tpro) REFERENCES Tuteur_Pro (id_tpro);

ALTER TABLE Tuteur_Pro ADD FOREIGN KEY (id_entp) REFERENCES Entreprise (id_entp);
