# Generated by Django 5.1.2 on 2024-10-16 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'verbose_name': 'Entreprise',
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'verbose_name': 'Professeur',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Salle',
            },
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'verbose_name': 'Secretaire',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('annee', models.IntegerField()),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professeur')),
            ],
            options={
                'verbose_name': 'Promotion',
            },
        ),
        migrations.CreateModel(
            name='AppStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entreprise')),
                ('tuteur_univ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professeur')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.promotion')),
            ],
            options={
                'verbose_name': 'AppStagiaire',
            },
        ),
        migrations.CreateModel(
            name='TuteurPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entreprise')),
            ],
            options={
                'verbose_name': 'TuteurPro',
            },
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('app_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.appstagiaire')),
                ('prof_candide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professeur')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salle')),
                ('tuteur_univ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuteur_univ', to='api.professeur')),
                ('tuteur_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuteur_pro', to='api.tuteurpro')),
            ],
            options={
                'verbose_name': 'Soutenance',
            },
        ),
        migrations.AddField(
            model_name='appstagiaire',
            name='tuteur_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tuteurpro'),
        ),
    ]
